"""Emit the on-disk structure of an Imperator module.

The layout mirrors the verified Hermes dashboard-plugin contract (see
``plugins/kanban/dashboard/``) so a scaffolded module installs, mounts and
removes through the mechanisms Hermes already ships — no fork of the router,
nav, or tool registry:

    plugins/<name>/
      dashboard/
        manifest.json     # {name,label,icon,tab:{path,position},entry,api?}
        capability.json    # the capability declaration (UI + agent tools)
        plugin_api.py      # optional FastAPI APIRouter → /api/plugins/<name>/
        README.md
        dist/              # JS bundle (built separately) — placeholder note

Capability-shaped modules need no ``plugin_api.py``: the shared Intelligence Hub
endpoints (``/api/entities``, ``/api/capabilities``) already serve their data,
and the tab renders ``CapabilityArea`` from the declaration. ``plugin_api.py`` is
emitted only when ``bespoke_api=True`` for modules that need their own endpoints.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_NAME_RE = re.compile(r"^[a-z][a-z0-9_-]*$")

# Nav positions the dashboard tab system understands (verified in web_server's
# dashboard-plugin discovery + the frontend buildNavItems): "end", or
# "after:<path-suffix>" / "before:<path-suffix>".
_DEFAULT_POSITION = "end"


@dataclass
class ModuleSpec:
    """Everything needed to emit a module. ``capability`` is a declaration dict
    in the shape ``hermes_cli.capabilities`` loads (id, label, entity, fields,
    optional lifecycle, views, agent.expose)."""

    name: str
    label: str
    icon: str = "package"
    capability: dict[str, Any] = field(default_factory=dict)
    position: str = _DEFAULT_POSITION
    bespoke_api: bool = False
    description: str = ""

    def validate(self) -> None:
        if not _NAME_RE.match(self.name or ""):
            raise ValueError(
                f"invalid module name {self.name!r} — must match [a-z][a-z0-9_-]*"
            )
        if not self.label:
            raise ValueError("module label is required")
        if self.capability:
            # Reuse the canonical validation the agent-tool generator relies on.
            for key in ("id", "label", "fields", "views"):
                if key not in self.capability:
                    raise ValueError(f"capability declaration missing {key!r}")


def _manifest(spec: ModuleSpec) -> dict[str, Any]:
    manifest: dict[str, Any] = {
        "name": spec.name,
        "label": spec.label,
        "description": spec.description or f"{spec.label} module",
        "icon": spec.icon,
        "version": "0.1.0",
        "tab": {"path": f"/{spec.name}", "position": spec.position},
        "entry": "dist/index.js",
        "css": "dist/style.css",
    }
    if spec.bespoke_api:
        manifest["api"] = "plugin_api.py"
    return manifest


_PLUGIN_API_TEMPLATE = '''"""Bespoke backend for the {label} module.

Mounted by the dashboard at ``/api/plugins/{name}/``. Keep destructive
operations behind the shared approval/audit path — do not auto-approve
sends/deletes here.
"""
from __future__ import annotations

from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
def health() -> dict:
    return {{"module": "{name}", "ok": True}}
'''

_README_TEMPLATE = """# {label} (Imperator module)

Generated by the Imperator module SDK. Structure mirrors a Hermes dashboard
plugin (see `plugins/kanban/dashboard/`).

- `manifest.json` — declares the `{path}` tab.
- `capability.json` — the declaration that drives the board/table/form UI **and**
  the agent tools (list/get auto; create/advance approval; no delete).
- `dist/` — the built JS bundle (build separately; not committed as source).
{api_line}
## Install / remove

Drop this directory under `plugins/` (bundled) or `~/.hermes/plugins/` (user),
then enable/disable it from the Modules page. Removing the directory removes the
module — no edits to the dashboard router, nav, or tool registry.
"""

_DIST_NOTE = (
    "// The module's tab bundle is built here (Vite → dist/index.js).\n"
    "// It renders <CapabilityArea capability={capability} /> from ../capability.json.\n"
)


def scaffold_module(target_root: Path | str, spec: ModuleSpec) -> Path:
    """Write ``spec`` as a module directory under ``target_root`` and return the
    created ``<target_root>/<name>/`` path. Refuses to overwrite an existing
    module directory."""
    spec.validate()
    root = Path(target_root)
    module_dir = root / spec.name
    dashboard_dir = module_dir / "dashboard"
    if module_dir.exists():
        raise FileExistsError(f"module directory already exists: {module_dir}")
    dashboard_dir.mkdir(parents=True)
    (dashboard_dir / "dist").mkdir()

    (dashboard_dir / "manifest.json").write_text(
        json.dumps(_manifest(spec), indent=2) + "\n", encoding="utf-8"
    )
    if spec.capability:
        (dashboard_dir / "capability.json").write_text(
            json.dumps(spec.capability, indent=2) + "\n", encoding="utf-8"
        )
    if spec.bespoke_api:
        (dashboard_dir / "plugin_api.py").write_text(
            _PLUGIN_API_TEMPLATE.format(name=spec.name, label=spec.label),
            encoding="utf-8",
        )
    (dashboard_dir / "dist" / ".gitkeep").write_text(_DIST_NOTE, encoding="utf-8")
    (dashboard_dir / "README.md").write_text(
        _README_TEMPLATE.format(
            label=spec.label,
            path=f"/{spec.name}",
            api_line=(
                "- `plugin_api.py` — bespoke endpoints mounted at "
                "`/api/plugins/%s/`.\n" % spec.name
                if spec.bespoke_api
                else ""
            ),
        ),
        encoding="utf-8",
    )
    return module_dir
